import { WaveDefaults } from '../constants.js';

// A rear Wasp row teaches dive telegraphs before later waves combine threats.
export const EARLY_WAVE_RECIPES = [
  {
    id: 'wave-1',
    band: 'training',
    hint: 'Aim steadily and use the open space to dodge incoming shots.',
    formation: { columns: 7, rows: 3, spacingX: 75, spacingY: 53, startY: 105 },
    enemyMix: [{ kind: 'scout', rows: [0, 1, 2] }],
    movement: { speed: WaveDefaults.baseSpeed * 0.8, dropDistance: WaveDefaults.dropDistance },
    firing: {
      initialDelay: 1.5,
      interval: 2.8,
      projectileSpeed: 150,
      pattern: 'random',
      maxProjectiles: 3,
    },
    diveCadence: null,
    maxDivers: 0,
    clearBonus: 250,
    noDamageBonus: 50,
    threatBudget: 21,
  },
  {
    id: 'wave-2',
    band: 'training',
    hint: 'Keep moving between shots as the formation closes in a little faster.',
    formation: { columns: 7, rows: 3, spacingX: 75, spacingY: 53, startY: 105 },
    enemyMix: [{ kind: 'scout', rows: [0, 1, 2] }],
    movement: { speed: WaveDefaults.baseSpeed, dropDistance: WaveDefaults.dropDistance },
    firing: {
      initialDelay: 1.35,
      interval: 2.35,
      projectileSpeed: 165,
      pattern: 'random',
      maxProjectiles: 4,
    },
    diveCadence: null,
    maxDivers: 0,
    clearBonus: 300,
    noDamageBonus: 60,
    threatBudget: 23,
  },
  {
    id: 'wave-3',
    band: 'telegraphs',
    hint: 'Watch for a glowing Wasp before it dives, then move clear of its path.',
    formation: { columns: 7, rows: 3, spacingX: 75, spacingY: 53, startY: 105 },
    enemyMix: [
      { kind: 'scout', rows: [0, 1, 2] },
      { kind: 'wasp', rows: [0], columns: [0, 1, 2, 3, 4, 5, 6] },
    ],
    movement: { speed: WaveDefaults.baseSpeed * 1.05, dropDistance: WaveDefaults.dropDistance },
    firing: {
      initialDelay: 1.3,
      interval: 1.9,
      projectileSpeed: 180,
      pattern: 'random',
      maxProjectiles: 5,
    },
    diveCadence: 7,
    maxDivers: 1,
    clearBonus: 350,
    noDamageBonus: 70,
    threatBudget: 31,
  },
  {
    id: 'wave-4',
    band: 'telegraphs',
    hint: 'Shots come faster, so read each Wasp warning and keep an escape lane open.',
    formation: { columns: 7, rows: 3, spacingX: 75, spacingY: 53, startY: 105 },
    enemyMix: [
      { kind: 'scout', rows: [0, 1, 2] },
      { kind: 'wasp', rows: [0], columns: [0, 1, 2, 3, 4, 5, 6] },
    ],
    movement: { speed: WaveDefaults.baseSpeed * 1.2, dropDistance: WaveDefaults.dropDistance },
    firing: {
      initialDelay: 1.2,
      interval: 1.6,
      projectileSpeed: 195,
      pattern: 'random',
      maxProjectiles: 6,
    },
    diveCadence: 6,
    maxDivers: 1,
    clearBonus: 400,
    noDamageBonus: 80,
    threatBudget: 33,
  },
];
