import { WaveDefaults } from '../constants.js';

const SENTINEL_ROW = 0;

function createRecipe({
  id,
  band,
  hint,
  columns,
  spacingX,
  startY,
  enemyMix,
  speedMultiplier,
  initialDelay,
  firingInterval,
  projectileSpeed,
  pattern,
  maxProjectiles,
  diveCadence,
  clearBonus,
  noDamageBonus,
  threatBudget,
}) {
  return Object.freeze({
    id,
    band,
    hint,
    formation: Object.freeze({
      columns,
      rows: 3,
      spacingX,
      spacingY: WaveDefaults.spacingY,
      startY,
    }),
    enemyMix: Object.freeze(enemyMix.map((entry) => Object.freeze({
      ...entry,
      rows: Object.freeze([...entry.rows]),
      ...(entry.columns ? { columns: Object.freeze([...entry.columns]) } : {}),
    }))),
    movement: Object.freeze({
      speed: WaveDefaults.baseSpeed * speedMultiplier,
      dropDistance: WaveDefaults.dropDistance,
    }),
    firing: Object.freeze({
      initialDelay,
      interval: firingInterval,
      projectileSpeed,
      pattern,
      maxProjectiles,
    }),
    diveCadence,
    maxDivers: 2,
    clearBonus,
    noDamageBonus,
    threatBudget,
  });
}

/**
 * Column-specific entries precede their row fallback so a rare Sentinel replaces
 * one Scout slot while staying in the safe top row of its formation.
 */
export const MIDDLE_WAVE_RECIPES = Object.freeze([
  createRecipe({
    id: 'wave-5',
    band: 'curves',
    hint: 'Watch the top row: one two-hit Sentinel guards the rear; keep moving through curved dives.',
    columns: 7,
    spacingX: 75,
    startY: 105,
    enemyMix: [
      { kind: 'sentinel', rows: [SENTINEL_ROW], columns: [3] },
      { kind: 'scout', rows: [SENTINEL_ROW, 2] },
      { kind: 'wasp', rows: [1] },
    ],
    speedMultiplier: 1.25,
    initialDelay: 0.9,
    firingInterval: 1.4,
    projectileSpeed: 230,
    pattern: 'random',
    maxProjectiles: 7,
    diveCadence: 5.4,
    clearBonus: 450,
    noDamageBonus: 90,
    threatBudget: 37,
  }),
  createRecipe({
    id: 'wave-6',
    band: 'curves',
    hint: 'Wasps fill the middle row; keep moving as faster curved dives cross the field.',
    columns: 7,
    spacingX: 75,
    startY: 105,
    enemyMix: [
      { kind: 'sentinel', rows: [SENTINEL_ROW], columns: [3] },
      { kind: 'wasp', rows: [2], columns: [1, 3, 5] },
      { kind: 'scout', rows: [SENTINEL_ROW, 2] },
      { kind: 'wasp', rows: [1] },
    ],
    speedMultiplier: 1.4,
    initialDelay: 0.85,
    firingInterval: 1.2,
    projectileSpeed: 250,
    pattern: 'random',
    maxProjectiles: 8,
    diveCadence: 5,
    clearBonus: 500,
    noDamageBonus: 100,
    threatBudget: 40,
  }),
  createRecipe({
    id: 'wave-7',
    band: 'crossfire',
    hint: 'Crossfire starts now: track the alternating shot lanes and keep changing position.',
    columns: 7,
    spacingX: 75,
    startY: 105,
    enemyMix: [
      { kind: 'sentinel', rows: [SENTINEL_ROW], columns: [3] },
      { kind: 'scout', rows: [SENTINEL_ROW] },
      { kind: 'wasp', rows: [1] },
      { kind: 'wasp', rows: [2], columns: [1, 3, 5, 6] },
      { kind: 'scout', rows: [2] },
    ],
    speedMultiplier: 1.45,
    initialDelay: 0.8,
    firingInterval: 1.05,
    projectileSpeed: 270,
    pattern: 'alternating-lanes',
    maxProjectiles: 9,
    diveCadence: 5.2,
    clearBonus: 550,
    noDamageBonus: 110,
    threatBudget: 43,
  }),
  createRecipe({
    id: 'wave-8',
    band: 'crossfire',
    hint: 'More Wasps join the alternating lanes; watch the gaps before committing to a side.',
    columns: 7,
    spacingX: 75,
    startY: 105,
    enemyMix: [
      { kind: 'sentinel', rows: [SENTINEL_ROW], columns: [3] },
      { kind: 'scout', rows: [SENTINEL_ROW] },
      { kind: 'wasp', rows: [1] },
      { kind: 'wasp', rows: [2], columns: [0, 1, 2, 4, 5] },
      { kind: 'scout', rows: [2] },
    ],
    speedMultiplier: 1.5,
    initialDelay: 0.75,
    firingInterval: 0.95,
    projectileSpeed: 290,
    pattern: 'alternating-lanes',
    maxProjectiles: 10,
    diveCadence: 4.9,
    clearBonus: 600,
    noDamageBonus: 120,
    threatBudget: 46,
  }),
  createRecipe({
    id: 'wave-9',
    band: 'crossfire',
    hint: 'Two Sentinels anchor the rear row while Wasps contest both firing lanes.',
    columns: 7,
    spacingX: 75,
    startY: 105,
    enemyMix: [
      { kind: 'sentinel', rows: [SENTINEL_ROW], columns: [2, 4] },
      { kind: 'scout', rows: [SENTINEL_ROW] },
      { kind: 'wasp', rows: [1, 2] },
    ],
    speedMultiplier: 1.6,
    initialDelay: 0.7,
    firingInterval: 0.85,
    projectileSpeed: 310,
    pattern: 'alternating-lanes',
    maxProjectiles: 10,
    diveCadence: 4.6,
    clearBonus: 650,
    noDamageBonus: 130,
    threatBudget: 49,
  }),
]);
